sudo: false
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - echo "skipping tests"
deploy:
  provider: heroku
  api-key:
    secure: K+k5IzztR4lZr3uElFn15A4wj3mrbpHianEXQ7n53685J9KtY1zhJWxeZUVpjfc/k8ib//BZsUF1AnchDSuar69f6AkAw88x6gNswB1dW10Y5tyNGJzE2r/cIAxvIJZl7qQxlVVUvaoTNRBN/qqif6ic/Cng6U5GXti9x1hL4AHxdHSXNjKFkHen+LkTdO30Yh6YM2tbPtk06sF4/Q7LPLkTPN3ycSBfzLolm8RJO7sK7Zy9dpl7IJq7yi3KrPPYiKRsi9NHagYJJiP2o/CdZmxNH1c6v/HfnPrB7q/zXYHm3YUIRXFRjVk1JivcWb9Q/aeOM+k+U5/hJvcx4hJSDng33XfwDoiGK3tyYmaKkC8Clpitzw/CFlF24MiXQf2pMLBYMdrctOHkUAV61CyK89U4TZAq2LLQntqO70kgTD6Q2rWt2N7lOF7QTv9gJDnkngYzzpm6nlXmICB07G7H695152utb5CQXO0hpeFrjFPyBiCXOoxG4DX4TucNBUejXEgRoetwMIuSmKTldUcEd6QzJk7MXfL3YkQZhLbwJS8ZTpuQlea5SxZ1vT/YfMc0blojwFimGH2yRUVF+MOUvfIxmvNqZ7CZbAMCas3WeZhdYi3NjbftzIIRanXFXsrQnqfgJU8ujrSyKBSB5rCAkFu2UkJqqCdyrbAwui+f76s=
  on:
    branch: prod
    repo: ZuraJaNai/ComputerVisionBB-API
