sudo: false
language: node_js
node_js:
  - 8
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - echo "skipping tests"
deploy:
  provider: heroku
  api-key:
    secure: j3hFgIWlI8DZv68I2pKLx3g8JPfLjuVEkNAipwhL1/6bllJZocukcjN7C/zM7+gRllZLFwxwtYlGugYpsK0EsEfh0Bfs0J8NKwiopHaj05FWr1cFQHZDyqjJu2F31p6RexPEN1B0mzD8PZ9/wAKFzqNmLN7tkgVSMWN4eV1y+DkSiwY/ahLj2o+O74n2fnPObjNJq+lJY6MV1SNT/CoMqeD3iohD75eldEG81T5yjmHi/125bHDtEivV8m9fylhOLVad72GbEJM6URbMXjNXdqdGnyzqVLB0bAtdFuAQ7hnYdh9WptawCAOsBk5dyqCfMbc9JQPs5dH+xHUfzU8mu22jMMQs8HR95lLmrlf0fAmMtWLnGbrMMzRJXtc3RDAbQCzgEJhT1Lfu4b6VzP5jruvo4LmF7TUQTPjgfHBeEFi0kiRbj4zSEvKim+yzg2NlcpR2ipsyIxt4T4ArQUfOQf6yYgm45eMUto7+537++Zd/xDmC0aowYWIzWXi+qdVyJPi0K4aICz4EX0zcVRp4XKRVrZaY2fbjPBtojtECpxP97HIZIn6qEqktUksCiBMO1THfWzWfHsnbGP36/IYmKwEVY8hh7LGbBXcbvCOqCaIYuUtmEaUjStC4YP56Aviat1M2faLjbTQFt2vdAQGFg10eC9dHnzfyHZ+vrhtcRfk=
    app: boundingboxes-api
  on:
    branch: prod
    repo: ZuraJaNai/ComputerVisionBB-API
